### ISSUE TITLE
Returning a Host not IP

### ISSUE THREAD

**Issue by team-pct** [watson/airplayer#2]
- Connected via iPhone Wifi 

Apple TV detected as Found Apple TV Device Device: ATV (2) at ATV.local

Could not start player.play 

Any solution ? 

Apple TV Model A1427
Software 7.2.1

Reference : https://github.com/popcorn-official/popcorn-desktop/commit/3a5c44bb16295e69b41c47f847d0b0970785d505

**Comment by watson** [comment]
We currently don't get the IP from the bonjour module. It's an outstanding feature that needs to be added. Most of the time this is not an issue though as the network should be able to figure it out using just the host name.

When you say that it will not start playing, can you be a little more precise in what happens?
- Do you get an error message?
- Does the TV turn black or change in any way for a second as if it's trying to play but nothing happens?
- What is the video codec of the video you are trying to play?

**Comment by swttt** [comment]
Might be related to the error i am receiving:

`Error: getaddrinfo ENOTFOUND Apple-TV.local Apple-TV.local:7000`
    `at errnoException (dns.js:27:10)`
    `at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)`

NOT RELATED:
Using it as an app for Homey home automation controller. It was a bug on their side, and is fixed now.
